[package]
name = "ifiend"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.23"
colored = "2.1.0"
csv = "1.3.1"
dirs = "5.0.1"
headless_chrome = "1.0.15"
open = "5.3.1"
serde = "1.0.216"
toml = "0.8.19"
